[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "dango-taxman"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[features]
# If enabled, Wasm exports won't be created. This allows this contract to be
# imported into other contracts as a library.
library = []
metrics = ["dep:metrics"]

[dependencies]
anyhow                = { workspace = true }
dango-account-factory = { workspace = true }
dango-oracle          = { workspace = true }
dango-types           = { workspace = true }
grug                  = { workspace = true }
grug-types            = { workspace = true }
metrics               = { workspace = true, optional = true }
