[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "pyth-types"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
anyhow              = { workspace = true }
byteorder           = { workspace = true }
data-encoding       = { workspace = true }
grug                = { workspace = true }
hex-literal         = { workspace = true }
pyth-lazer-protocol = { workspace = true }
pyth-sdk            = { workspace = true }
pythnet-sdk         = { workspace = true }
