protocol: quic
edge-ip-version: auto
ha-connections: 12
transport-loglevel: warn

ingress:
  - hostname: api-pr-{{ github_pr_number }}-{{ hostname }}.{{ dango_domain }}
    service: http://dango:8080
  - hostname: www-pr-{{ github_pr_number }}-{{ hostname }}.{{ dango_domain }}
    service: http://dango-frontend
  - hostname: faucet-pr-{{ github_pr_number }}-{{ hostname }}.{{ dango_domain }}
    service: http://faucet-bot:8082
  - hostname: graphiql-pr-{{ github_pr_number }}-{{ hostname }}.{{ dango_domain }}
    service: http://graphiql:80
  - service: http_status:404
