[book]
title        = "The Grug Book"
description  = "Everything you need for building apps on a Grug-powered chain"
authors      = ["Left Curve Software Ltd. (https://leftcurve.software/)"]
language     = "en"
multilingual = false
src          = "docs/"

[output.html]
git-repository-url = "https://github.com/left-curve/grug"

[build]
build-dir = "target/book/"

[rust]
edition = "2021"
