[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "dango-upgrade"
repository    = { workspace = true }
rust-version  = { workspace = true }

[dependencies]
dango-dex = { workspace = true }
grug      = { workspace = true }
grug-app  = { workspace = true }
tracing   = { workspace = true }
