[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "dango-upgrade"
repository    = { workspace = true }
rust-version  = { workspace = true }

[dependencies]
dango-account-factory = { workspace = true }
dango-types           = { workspace = true }
grug                  = { workspace = true }
grug-app              = { workspace = true }
tracing               = { workspace = true }
