[package]
edition = "2021"
name    = "indexer-sql-migration"
publish = false
version = "0.1.0"

[lib]
path = "src/lib.rs"

[dependencies]
async-std         = { workspace = true }
sea-orm-migration = { workspace = true }
tokio             = { workspace = true }
