protocol: quic
edge-ip-version: auto
ha-connections: 12
transport-loglevel: warn

ingress:
{% for dango_network in dango_networks %}
  - hostname: api-{{ dango_network }}-{{ hostname }}.{{ dango_domain }}
    service: http://traefik:{{ traefik[dango_network].ports.dango_port }}
  - hostname: graphiql-{{ dango_network }}-{{ hostname }}.{{ dango_domain }}
    service: http://traefik:{{ traefik[dango_network].ports.dango_port }}
  - hostname: www-{{ dango_network }}-{{ hostname }}.{{ dango_domain }}
    service: http://traefik:{{ traefik[dango_network].ports.dango_frontend_port }}
  - hostname: faucet-{{ dango_network }}-{{ hostname }}.{{ dango_domain }}
    service: http://traefik:{{ traefik[dango_network].ports.faucet_port }}
{% endfor %}
  - service: http_status:404
