[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "hyperlane-ism"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[features]
# If enabled, Wasm exports won't be created. This allows this contract to be
# imported into other contracts as a library.
library = []

[dependencies]
anyhow          = { workspace = true }
grug            = { workspace = true }
hyperlane-types = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
identity    = { workspace = true }
k256        = { workspace = true }
rand        = { workspace = true }
test-case   = { workspace = true }
