[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "grug-db-memory"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
grug-app    = { workspace = true }
grug-jmt    = { workspace = true }
grug-macros = { workspace = true }
grug-types  = { workspace = true }
thiserror   = { workspace = true }

[dev-dependencies]
