#:schema node_modules/wrangler/config-schema.json
compatibility_date  = "2024-10-04"
compatibility_flags = ["nodejs_compat"]
main                = "src/index.ts"
name                = "proxy-devserver"

[build]
command   = "pnpm build"
watch_dir = "src"

[observability]
enabled = true
