[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "dango-client"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
aes-gcm     = { workspace = true, features = ["std"] }
alloy       = { workspace = true }
anyhow      = { workspace = true }
async-trait = { workspace = true }
bip32       = { workspace = true }
dango-auth  = { workspace = true }
dango-types = { workspace = true }
grug        = { workspace = true }
identity    = { workspace = true }
k256        = { workspace = true }
pbkdf2      = { workspace = true }
rand        = { workspace = true }
sha2        = { workspace = true }

[dev-dependencies]
dango-account-factory = { workspace = true, features = ["library"] }
