services:
  validator:
    image: ghcr.io/left-curve/left-curve/hyperlane-agents:latest
    container_name: ${NETWORK}-validator
    env_file:
      - ./${NETWORK}.env
    volumes:
      - ./${NETWORK}_hyperlane_db:/app/hyperlane_db
      - ./config.json:/config/validator-config.json:ro
      - ../config.json:/config/config.json:ro
    environment:
      CONFIG_FILES: "/config/validator-config.json,/config/config.json"
    command: ["./validator"]
