[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "dango-scripts"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
anyhow         = { workspace = true }
async-trait    = { workspace = true }
dango-client   = { workspace = true }
dialoguer      = { workspace = true }
grug           = { workspace = true }
grug-app       = { workspace = true }
indexer-client = { workspace = true }
tokio          = { workspace = true }

[dev-dependencies]
chrono         = { workspace = true }
clap           = { workspace = true }
dango-genesis  = { workspace = true }
dango-testing  = { workspace = true }
dango-types    = { workspace = true }
grug-db-disk   = { workspace = true }
grug-db-memory = { workspace = true, features = ["snapshot"] }
grug-vm-rust   = { workspace = true }
hex            = { workspace = true }
hex-literal    = { workspace = true }
indexer-cache  = { workspace = true }
indexer-sql    = { workspace = true }
num-format     = { workspace = true }
tracing        = { workspace = true }
