[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "dango-scripts"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dev-dependencies]
alloy             = { workspace = true, features = ["contract", "full", "signer-mnemonic"] }
anyhow            = { workspace = true }
chrono            = { workspace = true }
clap              = { workspace = true }
dango-client      = { workspace = true }
dango-genesis     = { workspace = true }
dango-testing     = { workspace = true }
dango-types       = { workspace = true }
dotenvy           = { workspace = true }
grug              = { workspace = true }
grug-app          = { workspace = true }
grug-db-disk      = { workspace = true }
grug-db-memory    = { workspace = true, features = ["snapshot"] }
grug-vm-rust      = { workspace = true }
hex               = { workspace = true }
hex-literal       = { workspace = true }
hyperlane-testing = { workspace = true }
hyperlane-types   = { workspace = true }
indexer-cache     = { workspace = true }
indexer-client    = { workspace = true }
indexer-sql       = { workspace = true }
num-format        = { workspace = true }
reqwest           = { workspace = true }
serde             = { workspace = true, features = ["derive"] }
serde_json        = { workspace = true }
sha3              = { workspace = true }
tokio             = { workspace = true }
tracing           = { workspace = true }
