---
- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ uptimekuma_dir }}"
    - "{{ uptimekuma_dir }}/data"

- name: Deploy Uptime Kuma docker-compose
  become: true
  become_user: root
  template:
    src: "docker-compose.yml"
    dest: "{{ uptimekuma_dir }}/docker-compose.yml"
    owner: "{{ deploy_user }}"

- name: Launch Uptime Kuma stack
  community.docker.docker_compose_v2:
    project_src: "{{ uptimekuma_dir }}"
    pull: missing
    state: present
    recreate: always

