[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "dango-httpd"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
actix-web               = { workspace = true }
async-graphql           = { workspace = true }
async-graphql-actix-web = { workspace = true }
chrono                  = { workspace = true }
clap                    = { workspace = true }
dango-indexer-sql       = { workspace = true }
dango-types             = { workspace = true, features = ["async-graphql", "sea-orm"] }
indexer-httpd           = { workspace = true }
indexer-sql             = { workspace = true }
itertools               = { workspace = true }
sea-orm                 = { workspace = true }
serde                   = { workspace = true }
thiserror               = { workspace = true }
tokio                   = { workspace = true }
tracing                 = { workspace = true }
tracing-subscriber      = { workspace = true }
