[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "pyth-lazer"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
anyhow              = { workspace = true }
async-stream        = { workspace = true }
async-trait         = { workspace = true }
chrono              = { workspace = true }
grug                = { workspace = true }
grug-testing        = { workspace = true }
indexer-disk-saver  = { workspace = true }
pyth-client         = { workspace = true }
pyth-lazer-client   = { workspace = true }
pyth-lazer-protocol = { workspace = true }
pyth-types          = { workspace = true }
reqwest             = { workspace = true }
tokio               = { workspace = true }
tokio-stream        = { workspace = true }
tracing             = { workspace = true }
tracing-subscriber  = { workspace = true }
url                 = { workspace = true }

[dev-dependencies]
axum       = { workspace = true }
rand       = { workspace = true }
serde_json = { workspace = true }
