[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "grug-storage"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
bnum       = { workspace = true }
borsh      = { workspace = true }
grug-math  = { workspace = true }
grug-types = { workspace = true }
prost      = { workspace = true }
serde      = { workspace = true }

[dev-dependencies]
grug-types-base = { workspace = true }
test-case       = { workspace = true }
