[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "grug-math"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
bnum            = { workspace = true, features = ["borsh"] }
borsh           = { workspace = true, features = ["de_strict_order", "derive"] }
grug-macros     = { workspace = true }
grug-types-base = { workspace = true }
paste           = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
thiserror       = { workspace = true }

[dev-dependencies]
proptest   = { workspace = true }
serde_json = { workspace = true }
test-case  = { workspace = true }
