$ANSIBLE_VAULT;1.1;AES256
61383761646461346132396263306238636535343832653964313633303861613830303066663230
6139623735373934376631373361316566313164396132330a646433623866653237303332393138
64343132666662366666303738646632663638356261346334623035666433613932303438356337
3332383233643931350a633061343536366362316633313036353265643837616431623333626366
64303266333261363465346164636666333063303161393465663634303639343762376534353730
37613964353434343663336239363531363664303039613837626165353135363261393535326337
64323566376531343063623232653763326239346334323962313366623932623639646264383935
62353263316233373261616665336336336131303833633435316332383336626262666433396430
6138
