[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "grug-vm-hybrid"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
grug-app     = { workspace = true }
grug-macros  = { workspace = true }
grug-types   = { workspace = true }
grug-vm-rust = { workspace = true }
grug-vm-wasm = { workspace = true }
thiserror    = { workspace = true }
