[package]
authors       = { workspace = true }
categories    = { workspace = true }
description   = "Rust client for interacting with Grug via Tendermint RPC"
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "grug-rpc-client"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
anyhow         = { workspace = true }
grug-jmt       = { workspace = true }
grug-math      = { workspace = true }
grug-types     = { workspace = true }
serde          = { workspace = true }
tendermint     = { workspace = true }
tendermint-rpc = { workspace = true, features = ["http-client"] }
