[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "grug-vm-rust"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
elsa        = { workspace = true }
grug-app    = { workspace = true }
grug-crypto = { workspace = true }
grug-macros = { workspace = true }
grug-types  = { workspace = true }
serde       = { workspace = true }
thiserror   = { workspace = true }

[dev-dependencies]
grug-math    = { workspace = true }
grug-testing = { workspace = true }
test-case    = { workspace = true }
