---
tempo_dir: "{{ ansible_facts['env']['HOME'] }}/tempo"
tempo_port: 3200
tempo_otlp_grpc_port: 4317
tempo_otlp_http_port: 4318
tempo_jaeger_grpc_port: 14250
tempo_jaeger_http_port: 14268
tempo_jaeger_udp_compact_port: 6831
tempo_jaeger_udp_binary_port: 6832
