$ANSIBLE_VAULT;1.1;AES256
32626437376236376564633564323064326634616566396264326263616230303333663565393935
6530643135633163313763653765356166333438346263350a363432323465336130323366313137
65326665343435346363393138643464643365626535303730343638653264346466343530646533
3030653563623563640a313632393262653061653665303765393664343134323863343031613463
30636562343363663536346564396664643035393631633638353936623261666634366462633137
64666633353431623933636461366661313230646231376564303864333037373630643666366163
61353064643062333938306138386538373530333966303238653863653434373838623730396361
63643566343163346562
