services:
  relayer:
    image: ghcr.io/left-curve/left-curve/hyperlane-agents:latest
    container_name: ${NETWORK}-relayer
    env_file:
      - ./${NETWORK}.env
    volumes:
      - ./${NETWORK}_hyperlane_db:/app/hyperlane_db
      - ../config.json:/config/config.json:ro
    environment:
      CONFIG_FILES: "/config/config.json"
    command: ["./relayer"]
