services:
  validator:
    image: ghcr.io/left-curve/left-curve/hyperlane-agents:14b28143f239804b7769f0309d3c71e5c350b1b6
    env_file:
      - ./env/${NETWORK}.env
    volumes:
      - ./config/${NETWORK}.json:/config/${NETWORK}.json:ro
      - ../config/shared.json:/config/shared.json:ro
    environment:
      CONFIG_FILES: "/config/${NETWORK}.json,/config/shared.json"
    command: ["./relayer"]
