services:
  relayer:
    image: ghcr.io/left-curve/left-curve/hyperlane-agents:latest
    env_file:
      - ./env/${NETWORK}.env
    volumes:
      - ./config/${NETWORK}.json:/config/${NETWORK}.json:ro
      - ../config/shared.json:/config/shared.json:ro
    environment:
      CONFIG_FILES: "/config/${NETWORK}.json,/config/shared.json"
    command: ["./relayer"]
