[package]
name          = "grug-sdk"
description   = "Rust client for interacting with Grug chains"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
aes-gcm        = { workspace = true, features = ["std"] }
anyhow         = { workspace = true }
bip32          = { workspace = true }
grug-account   = { path = "../../contracts/account", features = ["library"] }
grug-crypto    = { path = "../../crates/crypto" }
grug-jmt       = { path = "../../crates/jellyfish-merkle" }
grug           = { path = "../../crates/std" }
hex            = { workspace = true }
# home           = { workspace = true }
k256           = { workspace = true }
pbkdf2         = { workspace = true }
rand           = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
sha2           = { workspace = true }
signature      = { workspace = true }
tendermint     = { workspace = true }
tendermint-rpc = { workspace = true, features = ["http-client"] }

[dev-dependencies]
