[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "grug-db-disk-lite"
repository    = { workspace = true }
rust-version  = { workspace = true }
version       = { workspace = true }

[dependencies]
grug-app    = { workspace = true }
grug-macros = { workspace = true }
grug-types  = { workspace = true }
rocksdb     = { workspace = true }
sha2        = { workspace = true }
tempfile    = { workspace = true }
thiserror   = { workspace = true }

[dev-dependencies]
temp-rocksdb = { workspace = true }
